
# notifications-gw project

To run the application you'll need Kafka running on port 9092.
To start kafka you can use the included `docker-compose.yaml` file and use it via `docker-compose up`

This project uses Quarkus, the Supersonic Subatomic Java Framework.

If you want to learn more about Quarkus, please visit its website: https://quarkus.io/ .

## Running the application in dev mode

You can run your application in dev mode that enables live coding using:
[source,shell]
----
./mvnw compile quarkus:dev
----

## Packaging and running the application

The application can be packaged using:
[source,shell]
----
./mvnw package
----

It produces the `notifications-gw-1.0.0-SNAPSHOT-runner.jar` file in the `/target` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `target/lib` directory.

If you want to build an _über-jar_, execute the following command:
[souce,shell]
----
./mvnw package -Dquarkus.package.type=uber-jar
----

The application is now runnable using `java -jar target/notifications-gw-1.0.0-SNAPSHOT-runner.jar`.

## Usage of the Clowder Config Source

This project uses the Clowder Config Source from https://github.com/RedHatInsights/clowder-quarkus-config-source To configure this source to use
a different file than `/cdappconfig/cdappconfig.json` you can use the property `clowder.file=/path/to/file.json`.

## Enabling the MockServer log during tests

This project uses link:https://www.mock-server.com[MockServer] to mock external services during the tests execution.

The MockServer log is disabled by default to reduce the noise in the application log.
It can be enabled by adding the following argument to the Maven build command:

```
-Dmockserver.logLevel=WARN|INFO|DEBUG|TRACE
```

Details about each MockServer log level are available in the link:https://www.mock-server.com/mock_server/debugging_issues.html[MockServer documentation].
