---
apiVersion: v1
kind: Template
metadata:
  name: notifications-gw-do-nothing
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: notifications-do-nothing-job-${IMAGE_TAG}
    annotations:
      ignore-check.kube-linter.io/unset-cpu-requirements : "Not required for this job that does nothing"  
      ignore-check.kube-linter.io/unset-memory-requirements : "Not required for this job that does nothing"    
  spec:
    template:
      spec:
        containers:
        - name: notifications-gw-do-nothing
          image: registry.access.redhat.com/ubi8-minimal:8.6-902.1661794353
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        restartPolicy: Never
parameters:
- name: IMAGE_TAG
  value: ''
  required: true

