/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.redhat.cloud.notifications.ingress;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class Action extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1443364343745473624L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Action\",\"namespace\":\"com.redhat.cloud.notifications.ingress\",\"fields\":[{\"name\":\"application\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"event_type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"string\",\"logicalType\":\"iso-8601\"}},{\"name\":\"account_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"payload\",\"type\":{\"type\":\"string\",\"logicalType\":\"json-object\"},\"default\":\"{}\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new com.redhat.cloud.notifications.avro.JsonObjectConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.LocalTimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new com.redhat.cloud.notifications.avro.Iso8601Conversion());
  }

  private static final BinaryMessageEncoder<Action> ENCODER =
      new BinaryMessageEncoder<Action>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Action> DECODER =
      new BinaryMessageDecoder<Action>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Action> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Action> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Action> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Action>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Action to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Action from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Action instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Action fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private String application;
   private String event_type;
   private java.time.LocalDateTime timestamp;
   private String account_id;
   private java.util.Map payload;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Action() {}

  /**
   * All-args constructor.
   * @param application The new value for application
   * @param event_type The new value for event_type
   * @param timestamp The new value for timestamp
   * @param account_id The new value for account_id
   * @param payload The new value for payload
   */
  public Action(String application, String event_type, java.time.LocalDateTime timestamp, String account_id, java.util.Map payload) {
    this.application = application;
    this.event_type = event_type;
    this.timestamp = timestamp;
    this.account_id = account_id;
    this.payload = payload;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return application;
    case 1: return event_type;
    case 2: return timestamp;
    case 3: return account_id;
    case 4: return payload;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new com.redhat.cloud.notifications.avro.Iso8601Conversion(),
      null,
      new com.redhat.cloud.notifications.avro.JsonObjectConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: application = value$ != null ? value$.toString() : null; break;
    case 1: event_type = value$ != null ? value$.toString() : null; break;
    case 2: timestamp = (java.time.LocalDateTime)value$; break;
    case 3: account_id = value$ != null ? value$.toString() : null; break;
    case 4: payload = (java.util.Map)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'application' field.
   * @return The value of the 'application' field.
   */
  public String getApplication() {
    return application;
  }


  /**
   * Sets the value of the 'application' field.
   * @param value the value to set.
   */
  public void setApplication(String value) {
    this.application = value;
  }

  /**
   * Gets the value of the 'event_type' field.
   * @return The value of the 'event_type' field.
   */
  public String getEventType() {
    return event_type;
  }


  /**
   * Sets the value of the 'event_type' field.
   * @param value the value to set.
   */
  public void setEventType(String value) {
    this.event_type = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.LocalDateTime getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.LocalDateTime value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'account_id' field.
   * @return The value of the 'account_id' field.
   */
  public String getAccountId() {
    return account_id;
  }


  /**
   * Sets the value of the 'account_id' field.
   * @param value the value to set.
   */
  public void setAccountId(String value) {
    this.account_id = value;
  }

  /**
   * Gets the value of the 'payload' field.
   * @return The value of the 'payload' field.
   */
  public java.util.Map getPayload() {
    return payload;
  }


  /**
   * Sets the value of the 'payload' field.
   * @param value the value to set.
   */
  public void setPayload(java.util.Map value) {
    this.payload = value;
  }

  /**
   * Creates a new Action RecordBuilder.
   * @return A new Action RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Action RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Action RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new Action RecordBuilder by copying an existing Action instance.
   * @param other The existing instance to copy.
   * @return A new Action RecordBuilder
   */
  public static Builder newBuilder(Action other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for Action instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Action>
    implements org.apache.avro.data.RecordBuilder<Action> {

    private String application;
    private String event_type;
    private java.time.LocalDateTime timestamp;
    private String account_id;
    private java.util.Map payload;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.application)) {
        this.application = data().deepCopy(fields()[0].schema(), other.application);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.event_type)) {
        this.event_type = data().deepCopy(fields()[1].schema(), other.event_type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.account_id)) {
        this.account_id = data().deepCopy(fields()[3].schema(), other.account_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.payload)) {
        this.payload = data().deepCopy(fields()[4].schema(), other.payload);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Action instance
     * @param other The existing instance to copy.
     */
    private Builder(Action other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.application)) {
        this.application = data().deepCopy(fields()[0].schema(), other.application);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.event_type)) {
        this.event_type = data().deepCopy(fields()[1].schema(), other.event_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.account_id)) {
        this.account_id = data().deepCopy(fields()[3].schema(), other.account_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.payload)) {
        this.payload = data().deepCopy(fields()[4].schema(), other.payload);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'application' field.
      * @return The value.
      */
    public String getApplication() {
      return application;
    }


    /**
      * Sets the value of the 'application' field.
      * @param value The value of 'application'.
      * @return This builder.
      */
    public Builder setApplication(String value) {
      validate(fields()[0], value);
      this.application = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'application' field has been set.
      * @return True if the 'application' field has been set, false otherwise.
      */
    public boolean hasApplication() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'application' field.
      * @return This builder.
      */
    public Builder clearApplication() {
      application = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'event_type' field.
      * @return The value.
      */
    public String getEventType() {
      return event_type;
    }


    /**
      * Sets the value of the 'event_type' field.
      * @param value The value of 'event_type'.
      * @return This builder.
      */
    public Builder setEventType(String value) {
      validate(fields()[1], value);
      this.event_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'event_type' field has been set.
      * @return True if the 'event_type' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'event_type' field.
      * @return This builder.
      */
    public Builder clearEventType() {
      event_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.LocalDateTime getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public Builder setTimestamp(java.time.LocalDateTime value) {
      validate(fields()[2], value);
      this.timestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'account_id' field.
      * @return The value.
      */
    public String getAccountId() {
      return account_id;
    }


    /**
      * Sets the value of the 'account_id' field.
      * @param value The value of 'account_id'.
      * @return This builder.
      */
    public Builder setAccountId(String value) {
      validate(fields()[3], value);
      this.account_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'account_id' field has been set.
      * @return True if the 'account_id' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'account_id' field.
      * @return This builder.
      */
    public Builder clearAccountId() {
      account_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'payload' field.
      * @return The value.
      */
    public java.util.Map getPayload() {
      return payload;
    }


    /**
      * Sets the value of the 'payload' field.
      * @param value The value of 'payload'.
      * @return This builder.
      */
    public Builder setPayload(java.util.Map value) {
      validate(fields()[4], value);
      this.payload = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'payload' field has been set.
      * @return True if the 'payload' field has been set, false otherwise.
      */
    public boolean hasPayload() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'payload' field.
      * @return This builder.
      */
    public Builder clearPayload() {
      payload = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Action build() {
      try {
        Action record = new Action();
        record.application = fieldSetFlags()[0] ? this.application : (String) defaultValue(fields()[0]);
        record.event_type = fieldSetFlags()[1] ? this.event_type : (String) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.time.LocalDateTime) defaultValue(fields()[2]);
        record.account_id = fieldSetFlags()[3] ? this.account_id : (String) defaultValue(fields()[3]);
        record.payload = fieldSetFlags()[4] ? this.payload : (java.util.Map) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Action>
    WRITER$ = (org.apache.avro.io.DatumWriter<Action>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Action>
    READER$ = (org.apache.avro.io.DatumReader<Action>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










